### ISSUE TITLE
DCモーター動作確認

### ISSUE THREAD

**Issue by Else156** [TDUSenjuAstronomyResearchClub/CanSat02#15]
DCモーター
RE-280RA-2865

- 秋月のリンク
  - <https://akizukidenshi.com/catalog/g/gP-06438/>

フルブリッジドライバＩＣ
BD6231F-E2

- 秋月のリンク
  - <https://akizukidenshi.com/catalog/g/gI-05088/>

**Comment by jinnosukeKato** [comment]
モーターとドライバの選定終わり次第取り組む

**Comment by jinnosukeKato** [comment]
基板につないだら勝手に回り始めた
回らなかったという検証報告もあるので、また試す

**Comment by Else156** [comment]
回路完成待ち

**Comment by jinnosukeKato** [comment]
動作
