### ISSUE TITLE
機体をゴールと一直線にするプログラムを作成

### ISSUE THREAD

**Issue by Else156** [TDUSenjuAstronomyResearchClub/CanSat02#25]
GitHubのexperimentファイルの中にあるdriving_test.pyのangle_adjustment関数を作成する

フローチャートにある以下の割り込み処理の部分はrunning.pyの中にあるLandingJudgement関数を参考に作ってほしい
![Image](https://github.com/TDUSenjuAstronomyResearchClub/CanSat02/assets/106682320/ba78e903-a25b-4ac1-8c79-374b15ff1ea3)

処理の流れは、以下のフローチャートのAngleAdjustment関数に示す
（フローチャートの関数名は大文字から小文字になっている）
https://github.com/TDUSenjuAstronomyResearchClub/CanSat02/blob/main/%E5%85%A8%E4%BD%93%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0.drawio.svg

**Comment by Else156** [comment]
AngleAdjustment(lat,lon)
目的地と機体を一直線にする

**Comment by Else156** [comment]
RunningSend
(filename,"機体と目的地を一直線にする")
|
|　間にある割り込み処理のプログラムは書かなくてよい
|
heading  = NineAxis.get_magnetic_heading

**Comment by jinnosukeKato** [comment]
関数名angle_adjustmentとしてすでにrunning.pyに定義されている関数の中身を書けば大丈夫です
is_straightがTrueになるまで回転すればいいんじゃないですかね
