### ISSUE TITLE
SeeValue関数をrunning.pyに記入する

### ISSUE THREAD

**Issue by Else156** [TDUSenjuAstronomyResearchClub/CanSat02#37]
running.pyをGitHubのrunningファイルに作成する

running.pyに以下の関数を実装する
SeeValue関数　　：send.pyにサンプル採取地点とゴールの緯度経度値を渡す関数

プログラム中でのコメントの書き方は以下のプログラムを参考にします。
https://github.com/TDUSenjuAstronomyResearchClub/CanSat02/blob/main/experiment/drop_test.py

処理の流れは、以下のフローチャートに示す
https://github.com/TDUSenjuAstronomyResearchClub/CanSat02/blob/main/%E5%85%A8%E4%BD%93%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0.drawio.svg

**Comment by jinnosukeKato** [comment]
RunningSendはXbee.send_msdにて実装

**Comment by jinnosukeKato** [comment]
グローバル変数の参照で解決
