### ISSUE TITLE
走行試験用の基盤の動作確認

### ISSUE THREAD

**Issue by Else156** [TDUSenjuAstronomyResearchClub/CanSat02#39]
drop_test.pyが動くか確認する

基盤に乗っているDCモータ、9軸センサ、GPS、超音波距離センサ、温湿度気圧センサ、気圧センサが正常に動作するか確認する

**Comment by jinnosukeKato** [comment]
I2Cがノイズで正常に動作せず
5/29, 30に修正予定

**Comment by jinnosukeKato** [comment]
ケーブルを使うもいまだ動かず
メッキ線を絶縁してみる
